//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HermesNet.WebServiceHermesNet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceHermesNet.WSHermesNetSoap")]
    public interface WSHermesNetSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje buscarLoginRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HermesNet.WebServiceHermesNet.buscarLoginResponse buscarLogin(HermesNet.WebServiceHermesNet.buscarLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje IngresarLoginRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HermesNet.WebServiceHermesNet.IngresarLoginResponse IngresarLogin(HermesNet.WebServiceHermesNet.IngresarLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ActualizarPasswdRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPasswd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HermesNet.WebServiceHermesNet.ActualizarPasswdResponse ActualizarPasswd(HermesNet.WebServiceHermesNet.ActualizarPasswdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje EliminarUsuarioRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HermesNet.WebServiceHermesNet.EliminarUsuarioResponse EliminarUsuario(HermesNet.WebServiceHermesNet.EliminarUsuarioRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WSHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string credencialesField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Credenciales {
            get {
                return this.credencialesField;
            }
            set {
                this.credencialesField = value;
                this.RaisePropertyChanged("Credenciales");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaGenericaWSVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaIngresoUsuarioVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaLoginVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string mensajeField;
        
        private int rutField;
        
        private char dvField;
        
        private string nombreUsuarioField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string mailField;
        
        private string cargoField;
        
        private string rolField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public char Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("NombreUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("ApellidoPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("ApellidoMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("Mail");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarLoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public HermesNet.WebServiceHermesNet.WSHeader WSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public buscarLoginRequest() {
        }
        
        public buscarLoginRequest(HermesNet.WebServiceHermesNet.WSHeader WSHeader, string username, string password) {
            this.WSHeader = WSHeader;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HermesNet.WebServiceHermesNet.RespuestaLoginVO buscarLoginResult;
        
        public buscarLoginResponse() {
        }
        
        public buscarLoginResponse(HermesNet.WebServiceHermesNet.RespuestaLoginVO buscarLoginResult) {
            this.buscarLoginResult = buscarLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IngresarLoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public HermesNet.WebServiceHermesNet.WSHeader WSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int rutUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public char dv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public long id_cargo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public long rol;
        
        public IngresarLoginRequest() {
        }
        
        public IngresarLoginRequest(HermesNet.WebServiceHermesNet.WSHeader WSHeader, int rutUsuario, char dv, string nombreUsuario, string apellidoPaterno, string apellidoMaterno, string mail, long id_cargo, string username, string password, long rol) {
            this.WSHeader = WSHeader;
            this.rutUsuario = rutUsuario;
            this.dv = dv;
            this.nombreUsuario = nombreUsuario;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.mail = mail;
            this.id_cargo = id_cargo;
            this.username = username;
            this.password = password;
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IngresarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HermesNet.WebServiceHermesNet.RespuestaIngresoUsuarioVO IngresarLoginResult;
        
        public IngresarLoginResponse() {
        }
        
        public IngresarLoginResponse(HermesNet.WebServiceHermesNet.RespuestaIngresoUsuarioVO IngresarLoginResult) {
            this.IngresarLoginResult = IngresarLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPasswd", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarPasswdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public HermesNet.WebServiceHermesNet.WSHeader WSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long rut;
        
        public ActualizarPasswdRequest() {
        }
        
        public ActualizarPasswdRequest(HermesNet.WebServiceHermesNet.WSHeader WSHeader, long rut) {
            this.WSHeader = WSHeader;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarPasswdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarPasswdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActualizarPasswdResult;
        
        public ActualizarPasswdResponse() {
        }
        
        public ActualizarPasswdResponse(bool ActualizarPasswdResult) {
            this.ActualizarPasswdResult = ActualizarPasswdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public HermesNet.WebServiceHermesNet.WSHeader WSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long rut;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(HermesNet.WebServiceHermesNet.WSHeader WSHeader, string username, long rut) {
            this.WSHeader = WSHeader;
            this.username = username;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HermesNet.WebServiceHermesNet.RespuestaGenericaWSVO EliminarUsuarioResult;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(HermesNet.WebServiceHermesNet.RespuestaGenericaWSVO EliminarUsuarioResult) {
            this.EliminarUsuarioResult = EliminarUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSHermesNetSoapChannel : HermesNet.WebServiceHermesNet.WSHermesNetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSHermesNetSoapClient : System.ServiceModel.ClientBase<HermesNet.WebServiceHermesNet.WSHermesNetSoap>, HermesNet.WebServiceHermesNet.WSHermesNetSoap {
        
        public WSHermesNetSoapClient() {
        }
        
        public WSHermesNetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSHermesNetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHermesNetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHermesNetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HermesNet.WebServiceHermesNet.buscarLoginResponse HermesNet.WebServiceHermesNet.WSHermesNetSoap.buscarLogin(HermesNet.WebServiceHermesNet.buscarLoginRequest request) {
            return base.Channel.buscarLogin(request);
        }
        
        public HermesNet.WebServiceHermesNet.RespuestaLoginVO buscarLogin(HermesNet.WebServiceHermesNet.WSHeader WSHeader, string username, string password) {
            HermesNet.WebServiceHermesNet.buscarLoginRequest inValue = new HermesNet.WebServiceHermesNet.buscarLoginRequest();
            inValue.WSHeader = WSHeader;
            inValue.username = username;
            inValue.password = password;
            HermesNet.WebServiceHermesNet.buscarLoginResponse retVal = ((HermesNet.WebServiceHermesNet.WSHermesNetSoap)(this)).buscarLogin(inValue);
            return retVal.buscarLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HermesNet.WebServiceHermesNet.IngresarLoginResponse HermesNet.WebServiceHermesNet.WSHermesNetSoap.IngresarLogin(HermesNet.WebServiceHermesNet.IngresarLoginRequest request) {
            return base.Channel.IngresarLogin(request);
        }
        
        public HermesNet.WebServiceHermesNet.RespuestaIngresoUsuarioVO IngresarLogin(HermesNet.WebServiceHermesNet.WSHeader WSHeader, int rutUsuario, char dv, string nombreUsuario, string apellidoPaterno, string apellidoMaterno, string mail, long id_cargo, string username, string password, long rol) {
            HermesNet.WebServiceHermesNet.IngresarLoginRequest inValue = new HermesNet.WebServiceHermesNet.IngresarLoginRequest();
            inValue.WSHeader = WSHeader;
            inValue.rutUsuario = rutUsuario;
            inValue.dv = dv;
            inValue.nombreUsuario = nombreUsuario;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.mail = mail;
            inValue.id_cargo = id_cargo;
            inValue.username = username;
            inValue.password = password;
            inValue.rol = rol;
            HermesNet.WebServiceHermesNet.IngresarLoginResponse retVal = ((HermesNet.WebServiceHermesNet.WSHermesNetSoap)(this)).IngresarLogin(inValue);
            return retVal.IngresarLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HermesNet.WebServiceHermesNet.ActualizarPasswdResponse HermesNet.WebServiceHermesNet.WSHermesNetSoap.ActualizarPasswd(HermesNet.WebServiceHermesNet.ActualizarPasswdRequest request) {
            return base.Channel.ActualizarPasswd(request);
        }
        
        public bool ActualizarPasswd(HermesNet.WebServiceHermesNet.WSHeader WSHeader, long rut) {
            HermesNet.WebServiceHermesNet.ActualizarPasswdRequest inValue = new HermesNet.WebServiceHermesNet.ActualizarPasswdRequest();
            inValue.WSHeader = WSHeader;
            inValue.rut = rut;
            HermesNet.WebServiceHermesNet.ActualizarPasswdResponse retVal = ((HermesNet.WebServiceHermesNet.WSHermesNetSoap)(this)).ActualizarPasswd(inValue);
            return retVal.ActualizarPasswdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HermesNet.WebServiceHermesNet.EliminarUsuarioResponse HermesNet.WebServiceHermesNet.WSHermesNetSoap.EliminarUsuario(HermesNet.WebServiceHermesNet.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public HermesNet.WebServiceHermesNet.RespuestaGenericaWSVO EliminarUsuario(HermesNet.WebServiceHermesNet.WSHeader WSHeader, string username, long rut) {
            HermesNet.WebServiceHermesNet.EliminarUsuarioRequest inValue = new HermesNet.WebServiceHermesNet.EliminarUsuarioRequest();
            inValue.WSHeader = WSHeader;
            inValue.username = username;
            inValue.rut = rut;
            HermesNet.WebServiceHermesNet.EliminarUsuarioResponse retVal = ((HermesNet.WebServiceHermesNet.WSHermesNetSoap)(this)).EliminarUsuario(inValue);
            return retVal.EliminarUsuarioResult;
        }
    }
}
